name = "ExamplePkg"
uuid = "9f148c02-bff7-4f90-9483-2a8e94e42d1d"
authors = ["aditi-gangadharan <nobody@nowhere.org>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Distributions = "0.25.122"
Test = "1.11.0"
